### ISSUE TITLE
LofiCreatureNamingView에서 변경한 이름이 이후 뷰에 적용되지 않음.

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MC3-G5T15-DreamEgg#102]
### 📝 작업 목적 / Miro / Figma

- 현재 LofiCreatureNamingView에서 이름 변경 시 Core Data에 업데이트하는 로직이 존재하지 않아 이름이 이후 뷰에서 변경된 이름이 적용되지 않습니다. 해당  로직을 구현합니다.
---

### 🛠️ Tasks

* [x] 이름 변경시 Core Data Update Logic 구현

**Comment by ValseLee** [comment]
이거 제가 가져가서 따로 할게요
어차피 지금 DailySleep coredata 쪽 리패토링이 필요할 것 같아서요

**Comment by ValseLee** [comment]
완료
